// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GitRepoLink
{
    internal sealed partial class Vsix
    {
        public const string Id = "GitRepoLink.5e87825c-6531-45fc-99f3-77e3de0e18db";
        public const string Name = "GitRepoLink";
        public const string Description = @"Visual Studio extension that  allowes so copy a link to the repository file of the current caret position.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Armando Aguirre";
        public const string Tags = "Git Devops Permalink";
    }
}
